### ISSUE TITLE
How SQL queries the results for paging?

### ISSUE THREAD

**Issue by tangyi90** [daveismyname/pagination#4]
How SQL queries the results for paging?

```php
if(isset($_POST['submit'])) {
	$stmt = $db->prepare('SELECT * FROM news WHERE Title LIKE ? '.$pages->get_limit());
	$stmt->execute(array("%$_POST[keywords]%"));
	$rs_list = array();
}else{
	$stmt = $db->prepare('SELECT * FROM news '.$pages->get_limit());
	$stmt->execute();
	$rs_list = array();
}
```

Find out the results of the page click on the next page appears all show

**Comment by daveismyname** [comment]
your first condition will only be true when there is a post request for the submit, another way would be to use $_GET for the filtering and pass all options from page to page so it will carry the options ie:

```php
$params = '&keywords='.$_GET['keywords'].'&submit='.$_GET['submit'];

$pages = new Paginator('100','p');
$pages->set_total(400);
$pages->page_links('?',$params);
```

Passing $param to page_links() would pass the params to each page via query strings.

**Comment by tangyi90** [comment]
Can you help me under the change?
I am a novice
This is my code

`<?php
//头部模版
require('header.php'); 
//左侧模版
require('menu.php'); 
//分页
include('../includes/paginator.php');
?>

 <div id="dcMain">
   
<div id="urHere">后台管理中心<b>></b><strong>新闻列表</strong> </div>   
	<div class="mainBox" style="height:auto!important;height:550px;min-height:550px;">
    <div class="filter">
    <form action="" method="post">
     <input name="keywords" type="text" class="inpMain" value="" size="20" />
     <input name="submit" class="btnGray" type="submit" value="搜索" />
    </form>
    <span>
        <h3><a href="news_add.php" class="actionBtn add">添加新闻</a></h3>
        </span>
    </div>
        <div id="list">
    <form name="action" method="post" action="">
    <table width="100%" border="0" cellpadding="8" cellspacing="0" class="tableBasic">
     <tr>
      <th width="22" align="center"><input name='chkall' type='checkbox' id='chkall' onclick='selectcheckbox(this.form)' value='check'></th>
      <th width="40" align="center">编号</th>
      <th align="left">新闻标题</th>
      <th width="80" align="center">状态</th>
      <th width="150" align="center">添加日期</th>
      <th width="80" align="center">操作</th>
     </tr>
	 <?php	
		try {
			//删除新闻
			if(isset($_GET['delpost'])){ 
				$ID_Dele= implode(",",$_POST['ID_Dele']); 
				$stmt = $db->prepare('DELETE FROM news WHERE ID = :ID  in ($ID_Dele)') ;
				$stmt->execute(array(':ID' => $_GET['delpost']));
				header('Location: news_manage.php');
				exit;
			}
			//设置每页显示多少条数
			$pages = new Paginator('10','p');
			
			if(isset($_POST['submit'])) {
				$stmt = $db->prepare('SELECT ID FROM news WHERE Title LIKE ?');
				$stmt->execute(array("%$_POST[keywords]%"));
				$row = $stmt->fetchAll();
			} else {
			//获取总ID数量
				$stmt = $db->prepare('SELECT ID FROM news');
				$stmt->execute();
				$row = $stmt->fetchAll();
			}
			
			//开始判断是够为空
			if(empty($row)) {
				$error[] = '没有文章!';
			}

			//传递ID数量
			$pages->set_total($stmt->rowCount());
			
			//查询数据库中的内容
			if(isset($_POST['submit'])) {
				$stmt = $db->prepare('SELECT * FROM news WHERE Title LIKE ? '.$pages->get_limit());
				$stmt->execute(array("%$_POST[keywords]%"));
				$rs_list = array();
			}else{
				$stmt = $db->prepare('SELECT * FROM news '.$pages->get_limit());
				$stmt->execute();
				$rs_list = array();
			}
			while($data = $stmt->fetch()){
				$rs_list[] = $data;
			}
			foreach ($rs_list as $val){ 	
			?>
     <tr>
      <td align="center"><input type="checkbox" name="checkbox[]" value="<?php echo $val['ID']; ?>" /></td>
      <td align="center"><?php echo $val['ID']; ?></td>
      <td><a href="article.php?rec=edit&id=10"><?php echo $val['Title']; ?></a></td>
      <td align="center"><a href="article.php?cat_id=1"><?php echo $val['Status']; ?></a></td>
      <td align="center"><?php echo $val['AddTime']; ?></td>
      <td align="center"><a href="news_edit.php?id=<?php echo $val['ID'];?>">编辑</a> | <a href="javascript:delpost('<?php echo $val['ID'];?>','<?php echo $val['Title'];?>')">删除</a></td>
 	</tr>
    <?php 
	}
    echo '</table>';

        	echo '<div class="list-page">'.$pages->page_links().'</div>';
		} catch(PDOException $e) {
			echo $e->getMessage();
		}
			if(isset($error)){ //显示错误信息
				foreach($error as $error){
					echo '<p class="bg-danger">'.$error.'</p>';
				}
			}
  	?>

    <div class="action">
     <select name="action" onchange="douAction()">
      <option value="0">请选择...</option>
      <option value="del_all">批量删除</option>
      <option value="category_move">批量激活</option>
     </select>
     <input name="submit" class="btn" type="submit" value="执行" />
    </div>
    </form>
    </div>
 </div>

<div class="clear"></div>
<?php require('footer.php'); ?>
<div class="clear"></div>
</div>
</body></html>
`
