### ISSUE TITLE
PHP 7.2 Error

### ISSUE THREAD

**Issue by jackttcoms** [daveismyname/pagination#6]
Hi, your class is amazing but for some reason i am getting an error ever since my upgrade to 7.2.

The error is thisbut when reviewing your code it all seems fine:
`Fatal error: Uncaught Error: Unsupported operand types in C:\xampp\htdocs\everything\app\helpers\pagination.php:50 Stack trace: #0 C:\xampp\htdocs\everything\app\controllers\Admin.php(28): Paginator->page_links() #1 C:\xampp\htdocs\everything\app\core\App.php(92): Admin->emailTemplates('') #2 C:\xampp\htdocs\everything\public\index.php(147): App->__construct(Array, Array) #3 {main} thrown in C:\xampp\htdocs\everything\app\helpers\pagination.php on line 50`

Could it be how I am counting which causes it?
```
        $results = $this->db->select('everything_email_templates', 'status >= 0 ORDER BY id DESC ' . $limit);
        if (!empty($results)) {
            $totalRows = count($results);
        }
        if ($results === FALSE) { $totalRows = 0; }
        return $totalRows;
```

Thanks very much in advance.

**Comment by daveismyname** [comment]
Thanks!

I've just ran this on php 7.2.13 I haven't been able to reproduce the error.

if it helps I ran this:

```php
$pages = new Paginator('1','p');

$stmt = $db->query('SELECT * FROM demo_news');
$total = $stmt->rowCount();

//pass number of records to
$pages->set_total($total); 

$data = $db->query('SELECT * FROM demo_news '.$pages->get_limit());
foreach($data as $row) {
	echo $row['title'].'<br>';
}

//create the page links
echo $pages->page_links();
```

**Comment by jackttcoms** [comment]
Hi thanks for your quick reply. I have found the issue is to do with the count function. 

`Warning: count(): Parameter must be an array or an object that implements Countable`. I did some research and now it works again. Sorry for the trouble.

**Comment by daveismyname** [comment]
ah yes, it's changed since 7.2.

Happy to hear you've solved it 👍

**Comment by jackttcoms** [comment]
I see you have changed from count() to $stmt->rowCount(); Was this due to the error? Thanks
